sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
script:
- npm run test
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: 46NGfTb6m47ZCvp0JzM388YSqfZe0O6EyBvJpoK+/L40eI5KL031hf4Yb0ikqxBh22SteSXbtgjetBMP7qcADC7nsNERh7p0vZhkdtbqvxKj3p38MpgtnMJ6RSwfFjpTRIOjCLpHna2L0StIRbTxcsz8iwYynALzljFVurnNAO1XW47UOZGoAFO3bOKBNZ6NRy50c9Lhz4oD92UnCM3eqst00hs3bM5hN3X294ObVOQHmRl+i7YulXoPe36bs/4S2OM4A5a9DeW/BEQ3gAYPTj9OyabuBOJttti6bYW2tTWPfYo6xSovyUMx9+UII9TItzQ9zhIR9KsIKQhRI9gc8ClDiOOVX+hlymB5jY+GccMGV1vqqlP5QxFmAEvMfy/w4iSL0JzXvn3KeraDpQIKRbudTIFIdEaxOigGJnXzTpAN0PoYRBVtZ8w4OPAuLoOjaprdQEdDeos5T23124ZCFcz8ejP0sTpv7mA9ITdwQ9M4pxUhdHpecNnEanS1jQD6Bh1WsMVdFOZQxRdUOE3iR7e3qUpaZh62famzXfRvqaCx9myKM9DZJbN0iuaq6bAVfUVl7h5DbPqGza6bBK7VQgfWyQt9eB0JD2pZeDIfPqz2gQYKPq+fc5Cf82TRc16pKbUS/z6iXpO+g7wFPtMXVkJsazESDBx3xky+JI+/HqU=
  - secure: ONrLufLz6JQwE/8p94HrTNQ6WY/CKC3V17S2zl6nguXJNO9DaLrN03JZU89N3K9sLfGf+6fB2ThytOv1PUzCdV2HU3BoqBQdaqcxjsI9Zxu9RZe1eN2AWAOpUUI4rWHXvlcEGWok6z54QIT3MLe+1Q62KwhkL7xTY0Lrs2si+aKkGw9F+sb6YP0zE+69z/SeTd3z18FN9dW4FchDab/CUyLulFRKkxMb71Vd+7L2dLoJP6HIf78zsW63LAqZ99pzYrz56onOn+8HhVZJT4kEESUk5Tlr8yeseXt/GQGkUASOZ0+YC7gOPweGny1LOyZfgOWNp7vyLxtEerPh+NWjazj6hfrVUIz5Yv7btrlxjh2bx72JdlEsvE8B6/8zfeVSyOJ3zq1F7BWy64nQ5nnl08n4u2RW9ukOen+AiF5y3HiPIe+pAt3yzoopytvltruCWeKggI/oC3NfR8+eGhAi+xcCuP0him30V5YqBXa/4oEYiw7ovXf90UqicVOTfWz66ZknbLs81keoL3M9oBb4YhwoZk5qp1RpluMEfhXIl2gxdG6q5Yb5Tz2h/tYVsZjLAKq1URf8Pz7Pu/+Qq3L+mBpTqDYhtc/KnMduuDypKUnBHuQSC7KyAr439KGdQ6A01tFEBe5rB1qk/gXjySmmOmiLmZ3jg39v4kOFJnA9620=
