sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
script:
- npm run test
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
    secure: oR/As20ZAsRQ7h8n08bNkCB/dxZXaaJLieT7KEstSwWB+R/YEYpv/VMp7jfr/oF07zkFuUCFTNjMr5EXP9MwrN3bLQAsdap+oq6OFCk35BcyZ2dRy2u5a1ZdIs6j2EvRZKPbEssPNyiHXMYYHMsKoCzIaXr1MaF283rU9gEQ4c9DeS/7v2enJwSz/cMC4fKRYME98MQnYsatSrdWPXxoG34orb+MRs9NzmYsT4UwhdsdgaiMO0cKEQcThK+PVCIQZ8rakmDJ3+fIQtxWaUXA42woQ90nu/tcYYaQSxiVmN8iQdFeWPNV9ZLguy5cNZseJ57WGyl3qeKuVf0jj7SAux94oKQsxFJJ4Pff+eUXdDl7bP2farYR5ggvhsk7BQrTILJOP0x0hLtcj5feP5mtsZNtbH3+bTydvu9LiBoqFoCwhMUYcoApWWbWBu8lkOVhfKhVa9YR8yRtNbAiSacwBra5qqDGT3hq/5wqfQdKBWSvAta0u8UY0S/U7hO+hontARX1qvThV/X6RL+OioftfB11c7VqbiRbHXQDgw/JXYRSuQelzSGu7y9E27TOFEvGcxyMNo9Ze+auyQmCxhK3udR3SFJIHXDPbNZKpE2MB/K1K/GeOSx44Q9Be8wR0iK2NhDp1p0dMngtOwX7PP94oWLgVJqaPVtsS/yApQEPCkY=
